# Generated by Django 5.1.2 on 2024-12-10 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_completionpost_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.challenge'),
        ),
    ]
