# Generated by Django 5.1.2 on 2024-12-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='completionpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
